// Generated by gencpp from file nlink_parser/LinktrackNode1.msg
// DO NOT EDIT!


#ifndef NLINK_PARSER_MESSAGE_LINKTRACKNODE1_H
#define NLINK_PARSER_MESSAGE_LINKTRACKNODE1_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nlink_parser
{
template <class ContainerAllocator>
struct LinktrackNode1_
{
  typedef LinktrackNode1_<ContainerAllocator> Type;

  LinktrackNode1_()
    : role(0)
    , id(0)
    , pos()  {
      pos.assign(0.0);
  }
  LinktrackNode1_(const ContainerAllocator& _alloc)
    : role(0)
    , id(0)
    , pos()  {
  (void)_alloc;
      pos.assign(0.0);
  }



   typedef uint8_t _role_type;
  _role_type role;

   typedef uint8_t _id_type;
  _id_type id;

   typedef boost::array<float, 3>  _pos_type;
  _pos_type pos;





  typedef boost::shared_ptr< ::nlink_parser::LinktrackNode1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nlink_parser::LinktrackNode1_<ContainerAllocator> const> ConstPtr;

}; // struct LinktrackNode1_

typedef ::nlink_parser::LinktrackNode1_<std::allocator<void> > LinktrackNode1;

typedef boost::shared_ptr< ::nlink_parser::LinktrackNode1 > LinktrackNode1Ptr;
typedef boost::shared_ptr< ::nlink_parser::LinktrackNode1 const> LinktrackNode1ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nlink_parser::LinktrackNode1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nlink_parser::LinktrackNode1_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nlink_parser::LinktrackNode1_<ContainerAllocator1> & lhs, const ::nlink_parser::LinktrackNode1_<ContainerAllocator2> & rhs)
{
  return lhs.role == rhs.role &&
    lhs.id == rhs.id &&
    lhs.pos == rhs.pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nlink_parser::LinktrackNode1_<ContainerAllocator1> & lhs, const ::nlink_parser::LinktrackNode1_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nlink_parser

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nlink_parser::LinktrackNode1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlink_parser::LinktrackNode1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlink_parser::LinktrackNode1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlink_parser::LinktrackNode1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlink_parser::LinktrackNode1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlink_parser::LinktrackNode1_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nlink_parser::LinktrackNode1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4cd6dde0524187c3a81d71bea105b5e5";
  }

  static const char* value(const ::nlink_parser::LinktrackNode1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4cd6dde0524187c3ULL;
  static const uint64_t static_value2 = 0xa81d71bea105b5e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::nlink_parser::LinktrackNode1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nlink_parser/LinktrackNode1";
  }

  static const char* value(const ::nlink_parser::LinktrackNode1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nlink_parser::LinktrackNode1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 role\n"
"uint8 id\n"
"float32[3] pos\n"
;
  }

  static const char* value(const ::nlink_parser::LinktrackNode1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nlink_parser::LinktrackNode1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.role);
      stream.next(m.id);
      stream.next(m.pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinktrackNode1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nlink_parser::LinktrackNode1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nlink_parser::LinktrackNode1_<ContainerAllocator>& v)
  {
    s << indent << "role: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.role);
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "pos[]" << std::endl;
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      s << indent << "  pos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NLINK_PARSER_MESSAGE_LINKTRACKNODE1_H
