// Generated by gencpp from file nlink_parser/TofsenseFrame0.msg
// DO NOT EDIT!


#ifndef NLINK_PARSER_MESSAGE_TOFSENSEFRAME0_H
#define NLINK_PARSER_MESSAGE_TOFSENSEFRAME0_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nlink_parser
{
template <class ContainerAllocator>
struct TofsenseFrame0_
{
  typedef TofsenseFrame0_<ContainerAllocator> Type;

  TofsenseFrame0_()
    : id(0)
    , systemTime(0)
    , distance(0.0)
    , distanceStatus(0)
    , signalStrength(0)  {
    }
  TofsenseFrame0_(const ContainerAllocator& _alloc)
    : id(0)
    , systemTime(0)
    , distance(0.0)
    , distanceStatus(0)
    , signalStrength(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint32_t _systemTime_type;
  _systemTime_type systemTime;

   typedef float _distance_type;
  _distance_type distance;

   typedef uint8_t _distanceStatus_type;
  _distanceStatus_type distanceStatus;

   typedef uint16_t _signalStrength_type;
  _signalStrength_type signalStrength;





  typedef boost::shared_ptr< ::nlink_parser::TofsenseFrame0_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nlink_parser::TofsenseFrame0_<ContainerAllocator> const> ConstPtr;

}; // struct TofsenseFrame0_

typedef ::nlink_parser::TofsenseFrame0_<std::allocator<void> > TofsenseFrame0;

typedef boost::shared_ptr< ::nlink_parser::TofsenseFrame0 > TofsenseFrame0Ptr;
typedef boost::shared_ptr< ::nlink_parser::TofsenseFrame0 const> TofsenseFrame0ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nlink_parser::TofsenseFrame0_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nlink_parser::TofsenseFrame0_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nlink_parser::TofsenseFrame0_<ContainerAllocator1> & lhs, const ::nlink_parser::TofsenseFrame0_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.systemTime == rhs.systemTime &&
    lhs.distance == rhs.distance &&
    lhs.distanceStatus == rhs.distanceStatus &&
    lhs.signalStrength == rhs.signalStrength;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nlink_parser::TofsenseFrame0_<ContainerAllocator1> & lhs, const ::nlink_parser::TofsenseFrame0_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nlink_parser

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nlink_parser::TofsenseFrame0_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlink_parser::TofsenseFrame0_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlink_parser::TofsenseFrame0_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlink_parser::TofsenseFrame0_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlink_parser::TofsenseFrame0_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlink_parser::TofsenseFrame0_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nlink_parser::TofsenseFrame0_<ContainerAllocator> >
{
  static const char* value()
  {
    return "517e0d95d3002f61857cbfd6276d7bc0";
  }

  static const char* value(const ::nlink_parser::TofsenseFrame0_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x517e0d95d3002f61ULL;
  static const uint64_t static_value2 = 0x857cbfd6276d7bc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::nlink_parser::TofsenseFrame0_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nlink_parser/TofsenseFrame0";
  }

  static const char* value(const ::nlink_parser::TofsenseFrame0_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nlink_parser::TofsenseFrame0_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"uint32 systemTime\n"
"float32 distance\n"
"uint8 distanceStatus\n"
"uint16 signalStrength\n"
;
  }

  static const char* value(const ::nlink_parser::TofsenseFrame0_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nlink_parser::TofsenseFrame0_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.systemTime);
      stream.next(m.distance);
      stream.next(m.distanceStatus);
      stream.next(m.signalStrength);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TofsenseFrame0_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nlink_parser::TofsenseFrame0_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nlink_parser::TofsenseFrame0_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "systemTime: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.systemTime);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "distanceStatus: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.distanceStatus);
    s << indent << "signalStrength: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.signalStrength);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NLINK_PARSER_MESSAGE_TOFSENSEFRAME0_H
