# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from nlink_parser/LinktrackNodeframe3.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import nlink_parser.msg

class LinktrackNodeframe3(genpy.Message):
  _md5sum = "956efca5fbd4c6b4e8ea7431078f8954"
  _type = "nlink_parser/LinktrackNodeframe3"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 role
uint8 id
uint32 localTime
uint32 systemTime
float32 voltage
LinktrackNode2[] node

================================================================================
MSG: nlink_parser/LinktrackNode2
uint8 role
uint8 id
float32 dis
float32 fpRssi
float32 rxRssi
"""
  __slots__ = ['role','id','localTime','systemTime','voltage','node']
  _slot_types = ['uint8','uint8','uint32','uint32','float32','nlink_parser/LinktrackNode2[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       role,id,localTime,systemTime,voltage,node

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LinktrackNodeframe3, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.role is None:
        self.role = 0
      if self.id is None:
        self.id = 0
      if self.localTime is None:
        self.localTime = 0
      if self.systemTime is None:
        self.systemTime = 0
      if self.voltage is None:
        self.voltage = 0.
      if self.node is None:
        self.node = []
    else:
      self.role = 0
      self.id = 0
      self.localTime = 0
      self.systemTime = 0
      self.voltage = 0.
      self.node = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B2If().pack(_x.role, _x.id, _x.localTime, _x.systemTime, _x.voltage))
      length = len(self.node)
      buff.write(_struct_I.pack(length))
      for val1 in self.node:
        _x = val1
        buff.write(_get_struct_2B3f().pack(_x.role, _x.id, _x.dis, _x.fpRssi, _x.rxRssi))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.node is None:
        self.node = None
      end = 0
      _x = self
      start = end
      end += 14
      (_x.role, _x.id, _x.localTime, _x.systemTime, _x.voltage,) = _get_struct_2B2If().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.node = []
      for i in range(0, length):
        val1 = nlink_parser.msg.LinktrackNode2()
        _x = val1
        start = end
        end += 14
        (_x.role, _x.id, _x.dis, _x.fpRssi, _x.rxRssi,) = _get_struct_2B3f().unpack(str[start:end])
        self.node.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B2If().pack(_x.role, _x.id, _x.localTime, _x.systemTime, _x.voltage))
      length = len(self.node)
      buff.write(_struct_I.pack(length))
      for val1 in self.node:
        _x = val1
        buff.write(_get_struct_2B3f().pack(_x.role, _x.id, _x.dis, _x.fpRssi, _x.rxRssi))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.node is None:
        self.node = None
      end = 0
      _x = self
      start = end
      end += 14
      (_x.role, _x.id, _x.localTime, _x.systemTime, _x.voltage,) = _get_struct_2B2If().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.node = []
      for i in range(0, length):
        val1 = nlink_parser.msg.LinktrackNode2()
        _x = val1
        start = end
        end += 14
        (_x.role, _x.id, _x.dis, _x.fpRssi, _x.rxRssi,) = _get_struct_2B3f().unpack(str[start:end])
        self.node.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B2If = None
def _get_struct_2B2If():
    global _struct_2B2If
    if _struct_2B2If is None:
        _struct_2B2If = struct.Struct("<2B2If")
    return _struct_2B2If
_struct_2B3f = None
def _get_struct_2B3f():
    global _struct_2B3f
    if _struct_2B3f is None:
        _struct_2B3f = struct.Struct("<2B3f")
    return _struct_2B3f
