# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from nlink_parser/TofsenseFrame0.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class TofsenseFrame0(genpy.Message):
  _md5sum = "517e0d95d3002f61857cbfd6276d7bc0"
  _type = "nlink_parser/TofsenseFrame0"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 id
uint32 systemTime
float32 distance
uint8 distanceStatus
uint16 signalStrength
"""
  __slots__ = ['id','systemTime','distance','distanceStatus','signalStrength']
  _slot_types = ['uint8','uint32','float32','uint8','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,systemTime,distance,distanceStatus,signalStrength

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TofsenseFrame0, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.systemTime is None:
        self.systemTime = 0
      if self.distance is None:
        self.distance = 0.
      if self.distanceStatus is None:
        self.distanceStatus = 0
      if self.signalStrength is None:
        self.signalStrength = 0
    else:
      self.id = 0
      self.systemTime = 0
      self.distance = 0.
      self.distanceStatus = 0
      self.signalStrength = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_BIfBH().pack(_x.id, _x.systemTime, _x.distance, _x.distanceStatus, _x.signalStrength))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.id, _x.systemTime, _x.distance, _x.distanceStatus, _x.signalStrength,) = _get_struct_BIfBH().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_BIfBH().pack(_x.id, _x.systemTime, _x.distance, _x.distanceStatus, _x.signalStrength))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.id, _x.systemTime, _x.distance, _x.distanceStatus, _x.signalStrength,) = _get_struct_BIfBH().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_BIfBH = None
def _get_struct_BIfBH():
    global _struct_BIfBH
    if _struct_BIfBH is None:
        _struct_BIfBH = struct.Struct("<BIfBH")
    return _struct_BIfBH
